### ISSUE TITLE
The module is affecting detection mode in v10

### ISSUE THREAD

**Issue by Foxaramar** [manuelVo/foundryvtt-socketlib#13]
With the module enabled, the detection modes in V10 no longer work, everything is visible.

**Comment by manuelVo** [comment]
Does this happen with only socketlib and no other modules enabled?

**Comment by JamzTheMan** [comment]
will there be a release for v10 or does this still work, just with deprecation warnings?

**Comment by manuelVo** [comment]
socketlib has already been released for v10 months ago, so I'm not sure what your inqury is

**Comment by JamzTheMan** [comment]
Sorry, I was going off the last "Release" per GitHub was 12 months ago and for v9. It didn't look like there had been a release for v10.

**Comment by jputman** [comment]
So I have determined that with just socketlib enabled, it seems that things like the invisible condition vs see invis works properly. But if you enable DF Convenient Effects it then stops working. But DF Convenient Effects alone without socketlib enable also works properly. So it appears to be a conflict between these two modules.
