### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by jacobwojoski** [manuelVo/foundryvtt-socketlib#14]
When adding socketlib as a dependency it cant find the module.json file at the default expected location to allow automatic downloader to work.

Also a section like this in the readme would have been nice although it doesn't allow the user to auto download. 
Instead it throws an error making the user manually search and download the file. 
```
"relationships": {
    "requires": [
      {
        "id": "socketlib",
        "type": "module"
      }
    ]
  }
```
Default Expected Location that it tried to get module.json is:
`https://github.com/manuelVo/foundryvtt-socketlib/releases/latest/download/module.json`

Updating module.json to the following also doesn't work and says it still cant find the module.json to auto download

```
"relationships": {
    "requires": [  
      {  
        "id": "socketlib",  
        "type": "module",  
	"manifest": "https://raw.githubusercontent.com/manuelVo/foundryvtt-socketlib/master/module.json",  
        "compatibility": {  
          "minimum": "10",  
          "verified": "10"  
        }  
      }  
    ]  
  }
```

**Comment by jacobwojoski** [comment]
Error Image: 
![image](https://user-images.githubusercontent.com/124112219/224854234-33c28621-3ed9-494e-ae4c-8c26322b65cf.png)

**Comment by jacobwojoski** [comment]
Best and easiest way I can see to fix would be to add module.json to release and it should then allow auto download to work correctly

**Comment by manuelVo** [comment]
Foundry (at least according to its documentation) doesn't have a "Default Expected Location" for manifests. There are two ways foundry tries to locate a module that's specified as a dependency. First it tries to look up the module id in the official FoundryVTT database. If a module is found with that id, foundry will install it from there. If the module doesn't exist in the database and there is no "manifest" entry specified in the dependency, the module installation will fail. If a manifest is specified, foundry will try to install from there.

That being said, it's unclear to me where Foundry is pulling the incorrect path from. The URL that foundry tries to access has never been a valid path to the socketlib manifest. Especially once you specify the correct manifest URL as you do in your second snippet Foundry should try to install the module from there.

My best guess at the moment is that there might be a module that uses socketlib as a dependency and specifies the incorrect manifest URL, confusing Foundry in the process. Can you check whether that might be the case?

**Comment by jacobwojoski** [comment]
I'll take another look later today when I have some time. But I believe my dev Env only has My module and Dice-So-Nice installed when testing. I'll remove everything and try again though.

**Comment by jacobwojoski** [comment]
My bad looks like it was on my end.
I tried updating the release after the fact with a new module.json doc and it didn't work for some reason so the zip had the wrong file. 

Still would say adding the relationship code snip to the readme would be nice but otherwise issue is closed. 
Thanks for the Mod. Works Great!
