### ISSUE TITLE
Update to v12

### ISSUE THREAD

**Issue by brunocalado** [manuelVo/foundryvtt-socketlib#20]
Hi.

Can you update your module to v12?

Thank you.

**Comment by weepingminotaur** [comment]
Would really appreciate this module getting a bump to v12.

**Comment by Championfire** [comment]
Took me a bit of work to figure out what was causing it but I isolated this module to be the cause of problems such as preventing compendium browsers to be opened. Sucks because a lot of good modules need it.

**Comment by manuelVo** [comment]
Implemented by #22
