### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by akrigline** [manuelVo/foundryvtt-socketlib#4]
Is there an open source license noted somewhere I am not finding for this repository? It would be great to link to as an example of implementing Sockets in Foundry, but if this code is [all rights reserved](https://choosealicense.com/no-permission/) (as implied by having no license) I don't think it's open game to use code from it in different projects. It also makes third-party contributions more questionable.

Wanted to ask about this to double check.

**Comment by tposney** [comment]
I love this module. It does what I should have done in my modules ages ago. However, I also have the same concern about the license, is it meant to be "open" and the lack of license is an oversight or is it mean to be all  rights reservered?

**Comment by manuelVo** [comment]
You could call the fact that this module doesn't have a license attached an oversight. Since obviously many people care about (and depend on) this module I'm licensing this under MIT, so people can actually go ahead and improve stuff in this module if they'd like to.
