### ISSUE TITLE
Disabled the "Escape" key from being used

### ISSUE THREAD

**Issue by Gray-Geist** [manuelVo/foundryvtt-socketlib#8]
I utilized "Find-the-Culprit" and narrowed down an issue where when selecting, for example, a character token, one cannot use the "Escape" key to exit the selection of said character token.

**Comment by manuelVo** [comment]
This sounds odd, as socketlib neither interacts with tokens, nor with keystrokes. Please double-check that this issue occurs with only socketlib and no other module enabled.

**Comment by Gray-Geist** [comment]
Thank you for fast response 👍 

Combat Ready! and Drag Ruler modules depend on socketlib. I disabled all three, then uninstalled socketlib and reinstalled. 

Combat Ready!, Drag Ruler, Socketlib modules disabled --> Escape key works --> Enable Socketlib alone --> Escape key does not work

(I went through the process of disabling all modules, and only socketlib, issue persists on it)

**Comment by manuelVo** [comment]
ESC works fine in my test world. Which version of Foundry, and which game system (and which version of the game system) are you using?

**Comment by Gray-Geist** [comment]
Appreciate the help. Narrowed it down with my dev, it was a bug in the Zweihander system and interacting that it pointed at your module somehow. Bug fix rolling out ASAP.
