### ISSUE TITLE
v10 testing results

### ISSUE THREAD

**Issue by akrigline** [manuelVo/foundryvtt-socketlib#9]
Leaving some input here about what little I have tested of this in core v10. If anyone else using this library has tested other methods, leave some notes and we can help manuelVo know what if anything needs attention for a v10 confirmed release.

Pieces that are working:
- `register`
- `executeAsUser`
- `executeForAllGMs`
- `executeForOtherGMs`
- `executeForEveryone`
- `executeForOthers`
- `executeForUsers`

Throws a compatibility warning but does appear to function:
- `executeAsGM`
    - method: `isResponsibleGM`
    - `socketlib.js:310:43`
    - `You are accessing the User#data object which is no longer used.`
- `registerModule`
    - method: `registerModule`
    - `socketlib.js:41:15`
    - `Error: You are accessing BasePackage#data which is now deprecated in favor of referencing schema fields directly on the BasePackage instance.`

**Comment by akrigline** [comment]
I believe that I've tested all of the api functionality related to modules (did not test `registerSystem`) and found no breakages, only some compatibility warnings.

**Comment by manuelVo** [comment]
Thanks for the effort. I've got a fairly comprehensive testing framework for socketlib, which should uncover all the v10 incompatibities automatically, so no manual testing should be required.

I'm on vacation currently, but I will work on making socketlib fit for v10 as soon as I return.

**Comment by schlosrat** [comment]
FYI, having this module loaded does break the core game's ability to display configuration settings.

**Comment by pdf** [comment]
@schlosrat I think you're mistaken, might want to take a look at your other modules.

**Comment by ZeroIchiro** [comment]
Additional Info from the Browser Console:

[socketlib] The module "socketlib" is using "name" which is deprecated in favor of "id" [setup.js:145:17](http://example.com:30404/scripts/setup.js)
[socketlib] The module "socketlib" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

**Comment by sPOiDar** [comment]
@ZeroIchiro those warnings on the setup page unfortunately show for all modules that want to maintain backwards compatability with v9 in a single release, even if they already include the correct v10 metadata, so expect to see those for a lot of modules, for the foreseeable future (until Foundry either fixes the warning logic, or v11 rolls around).

**Comment by brunocalado** [comment]
I'm receiving this warn. IS there a way to remove it?

![image](https://user-images.githubusercontent.com/4999783/193131433-f0a715ae-b0fb-44c8-b216-16f5cbccc174.png)

hand.js
`this.socket = socketlib.registerModule(this.moduleName);       	`

module.js
`let handRaiser = new HandRaiser();`

**Comment by manuelVo** [comment]
Unfortunately, there is nothing you can do against this warning. It will be addressed in a future socketlib release. Be assured though that socketlib has been tested thoroughly and will work as expected despite the warning.

**Comment by manuelVo** [comment]
This warning should be gone in the latest socketlib release
